---
- name: Get Device Facts
  hosts: srx
  connection: local
  gather_facts: no

  tasks:
    - name: Check NETCONF connectivity
      ansible.builtin.wait_for: 
        host: "{{ inventory_hostname }}"
        port: 830 
        timeout: 5